version: '2'
services:
  app:
    image: ruby:2.3.2
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rails server -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/nursing-form
    ports:
      - "3000:3000"
    links:
      - postgres
  postgres:
    image: postgres
    ports:
      - "5432"
    environment:
      - POSTGRES_DB=nursingform_development
      - POSTGRES_PASSWORD=Ttnkf@g2011!
