class AddSkinRiskAssessmentScreenToSubmission < ActiveRecord::Migration[5.0]
  def change
    add_column :submissions, :sensory_perception, :string
    add_column :submissions, :completely_limited, :integer
    add_column :submissions, :very_limited, :integer
    add_column :submissions, :slightly_limited, :integer
    add_column :submissions, :no_impairment, :integer
    add_column :submissions, :moisture, :string
    add_column :submissions, :constantly_moist, :integer
    add_column :submissions, :moist, :integer
    add_column :submissions, :occasionally_moist, :integer
    add_column :submissions, :rarely_moist, :integer
    add_column :submissions, :activity, :string
    add_column :submissions, :bedfast, :integer
    add_column :submissions, :chairfast, :integer
    add_column :submissions, :walks_occasionally, :integer
    add_column :submissions, :walks_frequently, :integer
    add_column :submissions, :mobility, :string
    add_column :submissions, :completely_immobile, :integer
    add_column :submissions, :very_limited, :integer
    add_column :submissions, :slightly_limited, :integer
    add_column :submissions, :no_limitations, :integer
    add_column :submissions, :nutrition_score, :string
    add_column :submissions, :very_poor, :integer
    add_column :submissions, :probably_inadequate, :integer
    add_column :submissions, :adequate, :integer
    add_column :submissions, :excellent, :integer
    add_column :submissions, :friction_shear, :string
    add_column :submissions, :problem, :integer
    add_column :submissions, :potential_problem, :integer
    add_column :submissions, :no_apparent_problem, :integer
    add_column :submissions, :total_score, :integer
    add_column :submissions, :skin_intact, :string
    add_column :submissions, :pressure_ulcer_prevention_protocol_in_place, :string
    add_column :submissions, :see_presssure_ulcer_documentation_form, :string
    add_column :submissions, :fall_scale_risk, :string
    add_column :submissions, :history_of_falling, :string
    add_column :submissions, :no, :integer
    add_column :submissions, :immediate_or_within_three_months, :integer
    add_column :submissions, :presence_of_secondary_diagnosis, :string
    add_column :submissions, :no, :integer
    add_column :submissions, :yes, :integer
    add_column :submissions, :ambulatory_aid, :string
    add_column :submissions, :none_bedrest_nurse_assist, :integer
    add_column :submissions, :cane_walker_crutches, :integer
    add_column :submissions, :furniture, :integer
    add_column :submissions, :iv_heparin_lock, :string
    add_column :submissions, :no, :integer
    add_column :submissions, :yes, :integer
    add_column :submissions, :gait_transferring, :string
    add_column :submissions, :normal_bedrest_wheelchair, :integer
    add_column :submissions, :weak, :integer
    add_column :submissions, :impaired, :integer
    add_column :submissions, :mental_status, :string
    add_column :submissions, :oriented_to_own_ability, :integer
    add_column :submissions, :overstimates_forgets_limitations, :integer
    add_column :submissions, :total_score, :integer
    add_column :submissions, :greater_than_25_initiate_fall_risk_measures, :string
    add_column :submissions, :patient_refuses_to_wear_red_slippers_in_bed, :string
    add_column :submissions, :unable_to_wear_slippers, :string
    add_column :submissions, :sign_on_door, :string
    add_column :submissions, :medications, :string
  end
end
