class AddFieldsToLab < ActiveRecord::Migration[5.0]
  def change
    add_column :labs, :coagulation_therapy, :string
    add_column :labs, :patient_fasting, :string
    add_column :labs, :ventilator, :string
    add_column :labs, :urinalysis, :string
    add_column :labs, :wbc, :float
    add_column :labs, :rbc, :float
    add_column :labs, :hgb, :float
    add_column :labs, :hct, :float
    add_column :labs, :plt, :float
    add_column :labs, :glucose, :float
    add_column :labs, :bun, :float
    add_column :labs, :co2, :float
    add_column :labs, :chloride, :float
    add_column :labs, :creatinine, :float
    add_column :labs, :sodium, :float
    add_column :labs, :potassium, :float
    add_column :labs, :magnesium, :float
    add_column :labs, :phosphorus, :float
    add_column :labs, :calcium, :float
    add_column :labs, :appearance, :string
    add_column :labs, :sp_gravity, :float
    add_column :labs, :color_ua, :string
    add_column :labs, :ph, :float
    add_column :labs, :protein, :string
    add_column :labs, :glucose_ua, :string
    add_column :labs, :ketones, :string
    add_column :labs, :bilirubin, :string
    add_column :labs, :occult_blood, :string
    add_column :labs, :wbc_ua, :string
    add_column :labs, :rbc_ua, :string
    add_column :labs, :ck, :float
    add_column :labs, :ck_mb, :float
    add_column :labs, :trop, :float
    add_column :labs, :myoglobin, :float
    add_column :labs, :pt, :float
    add_column :labs, :ptt, :float
    add_column :labs, :inr, :float
    add_column :labs, :alkaline_phos, :float
    add_column :labs, :albumin, :float
    add_column :labs, :bilirubin_direct, :float
    add_column :labs, :bilirubin_total, :float
    add_column :labs, :ast, :float
    add_column :labs, :alt, :float
    add_column :labs, :cholesterol, :float
    add_column :labs, :triglycerides, :float
    add_column :labs, :hdl, :float
    add_column :labs, :ldl, :float
    add_column :labs, :digoxin, :float
    add_column :labs, :dilantin, :float
    add_column :labs, :gentamicin, :float
    add_column :labs, :gentamicin_trough, :float
    add_column :labs, :vancomycin, :float
    add_column :labs, :vancomycin_trough, :float
    add_column :labs, :ph_abg, :float
    add_column :labs, :pco2, :float
    add_column :labs, :hco3, :float
    add_column :labs, :po2, :float
    add_column :labs, :fio2, :float
    add_column :labs, :lactic_acid, :float
    add_column :labs, :bnp, :float
    add_column :labs, :patient_lab_name, :string
    add_column :labs, :mr_number_lab, :integer
    add_column :labs, :room_number, :integer
  end
end
