class AddFieldsToLab < ActiveRecord::Migration[5.0]
  def change
    add_column :labs, :coagulation_therapy, :string
    add_column :labs, :patient_fasting, :string
    add_column :labs, :ventilator, :string
    add_column :labs, :urinalysis, :string
    add_column :labs, :wbc, :integer
    add_column :labs, :rbc, :integer
    add_column :labs, :hgb, :integer
    add_column :labs, :hct, :integer
    add_column :labs, :plt, :integer
    add_column :labs, :glucose, :integer
    add_column :labs, :bun, :integer
    add_column :labs, :co2, :integer
    add_column :labs, :chloride, :integer
    add_column :labs, :creatinine, :integer
    add_column :labs, :sodium, :integer
    add_column :labs, :potassium, :integer
    add_column :labs, :magnesium, :integer
    add_column :labs, :phosphorus, :integer
    add_column :labs, :calcium, :integer
    add_column :labs, :appearance, :string
    add_column :labs, :sp_gravity, :integer
    add_column :labs, :color_ua, :string
    add_column :labs, :ph, :integer
    add_column :labs, :protein, :string
    add_column :labs, :glucose_ua, :string
    add_column :labs, :ketones, :string
    add_column :labs, :bilirubin, :string
    add_column :labs, :occult_blood, :string
    add_column :labs, :wbc_ua, :string
    add_column :labs, :rbc_ua, :string
    add_column :labs, :ck, :integer
    add_column :labs, :ck_mb, :integer
    add_column :labs, :trop, :integer
    add_column :labs, :myoglobin, :integer
    add_column :labs, :pt, :integer
    add_column :labs, :ptt, :integer
    add_column :labs, :inr, :integer
    add_column :labs, :alkaline_phos, :integer
    add_column :labs, :albumin, :integer
    add_column :labs, :bilirubin, :integer
    add_column :labs, :bilirubin_total, :integer
    add_column :labs, :ast, :integer
    add_column :labs, :alt, :integer
    add_column :labs, :cholesterol, :integer
    add_column :labs, :triglycerides, :integer
    add_column :labs, :hdl, :integer
    add_column :labs, :ldl, :integer
    add_column :labs, :digoxin, :integer
    add_column :labs, :dilantin, :integer
    add_column :labs, :gentamicin, :integer
    add_column :labs, :gentamicin_trough, :integer
    add_column :labs, :vancomycin, :integer
    add_column :labs, :vancomycin_trough, :integer
    add_column :labs, :ph_abg, :integer
    add_column :labs, :pco2, :integer
    add_column :labs, :hco3, :integer
    add_column :labs, :po2, :integer
    add_column :labs, :fio2, :integer
    add_column :labs, :lactic_acid, :integer
    add_column :labs, :bnp, :integer
    add_column :labs, :patient_lab_name, :string
    add_column :labs, :mr_number_lab, :integer
    add_column :labs, :room_number, :integer
  end
end
