class Lab < ApplicationRecord
  belongs_to :history
  has_one :patient, through: :history

  def add_data_to_lab_object(data)
    self.orders = data["orders"]
    self.date_and_time_drawn = data["date_and_time_drawn"]
    self.coagulation_therapy = data["coagulation_therapy"]
    self.patient_fasting = data["patient_fasting"]
    self.ventilator = data["ventilator"]
    self.urinalysis = data["urinalysis"]
    self.wbc = data["wbc"]
    self.rbc = data["rbc"]
    self.hgb = data["hgb"]
    self.hct = data["hct"]
    self.plt = data["plt"]
    self.glucose = data["glucose"]
    self.bun = data["bun"]
    self.co2 = data["co2"]
    self.chloride = data["chloride"]
    self.creatinine = data["creatinine"]
    self.sodium = data["sodium"]
    self.potassium = data["potassium"]
    self.magnesium = data["magnesium"]
    self.phosphorus = data["phosphorus"]
    self.calcium = data["calcium"]
    self.appearance = data["appearance"]
    self.sp_gravity = data["sp_gravity"]
    self.color_ua = data["color_ua"]
    self.ph = data["ph"]
    self.protein = data["protein"]
    self.glucose_ua = data["glucose_ua"]
    self.ketones = data["ketones"]
    self.bilirubin = data["bilirubin"]
    self.occult_blood = data["occult_blood"]
    self.wbc_ua = data["wbc_ua"]
    self.rbc_ua = data["rbc_ua"]
    self.ck = data["ck"]
    self.ck_mb = data["ck_mb"]
    self.trop = data["trop"]
    self.myoglobin = data["myoglobin"]
    self.pt = data["pt"]
    self.ptt = data["ptt"]
    self.inr = data["inr"]
    self.alkaline_phos = data["alkaline_phos"]
    self.albumin = data["albumin"]
    self.bilirubin_direct = data["bilirubin_direct"]
    self.bilirubin_total = data["bilirubin_total"]
    self.ast = data["ast"]
    self.alt = data["alt"]
    self.cholesterol = data["cholesterol"]
    self.triglycerides = data["triglycerides"]
    self.hdl = data["hdl"]
    self.ldl = data["ldl"]
    self.digoxin = data["digoxin"]
    self.dilantin = data["dilantin"]
    self.gentamicin = data["gentamicin"]
    self.gentamicin_trough = data["gentamicin_trough"]
    self.vancomycin = data["vancomycin"]
    self.vancomycin_trough = data["vancomycin_trough"]
    self.ph_abg = data["ph_abg"]
    self.pco2 = data["pco2"]
    self.hco3 = data["hco3"]
    self.po2 = data["po2"]
    self.fio2 = data["fio2"]
    self.lactic_acid = data["lactic_acid"]
    self.bnp = data["bnp"]
    self.patient_lab_name = data["patient_lab_name"]
    self.mr_number_lab = data["mr_number_lab"]
    self.room_number = data["room_number"]
    byebug
  end
end
